/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TryOnIdRouteImport } from './routes/try-on.$id'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as SareeIdRouteImport } from './routes/saree.$id'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as AdminSareesRouteImport } from './routes/admin.sarees'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCatalogsRouteImport } from './routes/admin.catalogs'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnIdRoute = TryOnIdRouteImport.update({
  id: '/try-on/$id',
  path: '/try-on/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SareeIdRoute = SareeIdRouteImport.update({
  id: '/saree/$id',
  path: '/saree/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSareesRoute = AdminSareesRouteImport.update({
  id: '/admin/sarees',
  path: '/admin/sarees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogsRoute = AdminCatalogsRouteImport.update({
  id: '/admin/catalogs',
  path: '/admin/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/admin/catalogs': typeof AdminCatalogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/sarees': typeof AdminSareesRoute
  '/result/$id': typeof ResultIdRoute
  '/saree/$id': typeof SareeIdRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/try-on/$id': typeof TryOnIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/admin/catalogs': typeof AdminCatalogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/sarees': typeof AdminSareesRoute
  '/result/$id': typeof ResultIdRoute
  '/saree/$id': typeof SareeIdRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/try-on/$id': typeof TryOnIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/admin/catalogs': typeof AdminCatalogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/sarees': typeof AdminSareesRoute
  '/result/$id': typeof ResultIdRoute
  '/saree/$id': typeof SareeIdRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/try-on/$id': typeof TryOnIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/admin/catalogs'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/sarees'
    | '/result/$id'
    | '/saree/$id'
    | '/superadmin/dashboard'
    | '/try-on/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/admin/catalogs'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/sarees'
    | '/result/$id'
    | '/saree/$id'
    | '/superadmin/dashboard'
    | '/try-on/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/admin/catalogs'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/admin/sarees'
    | '/result/$id'
    | '/saree/$id'
    | '/superadmin/dashboard'
    | '/try-on/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  AdminCatalogsRoute: typeof AdminCatalogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSareesRoute: typeof AdminSareesRoute
  ResultIdRoute: typeof ResultIdRoute
  SareeIdRoute: typeof SareeIdRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  TryOnIdRoute: typeof TryOnIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on/$id': {
      id: '/try-on/$id'
      path: '/try-on/$id'
      fullPath: '/try-on/$id'
      preLoaderRoute: typeof TryOnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saree/$id': {
      id: '/saree/$id'
      path: '/saree/$id'
      fullPath: '/saree/$id'
      preLoaderRoute: typeof SareeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sarees': {
      id: '/admin/sarees'
      path: '/admin/sarees'
      fullPath: '/admin/sarees'
      preLoaderRoute: typeof AdminSareesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogs': {
      id: '/admin/catalogs'
      path: '/admin/catalogs'
      fullPath: '/admin/catalogs'
      preLoaderRoute: typeof AdminCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  AdminCatalogsRoute: AdminCatalogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSareesRoute: AdminSareesRoute,
  ResultIdRoute: ResultIdRoute,
  SareeIdRoute: SareeIdRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  TryOnIdRoute: TryOnIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
